use alloc::collections::{BTreeMap, BTreeSet};
use core::error::Error;
use std::fs;

use heck::ToShoutySnakeCase as _;
use quote::{format_ident, quote};
use ungrammar::Grammar;

const GRAMMAR: &str = "grammar/schema.ungram";
const OUTPUT: &str = "src/schema/syntax.rs";

const PUNCTUATION: &[(&str, &str)] = &[
    ("@", "AT"),
    ("(", "L_PAREN"),
    (")", "R_PAREN"),
    ("{", "L_BRACE"),
    ("}", "R_BRACE"),
    ("[", "L_BRACKET"),
    ("]", "R_BRACKET"),
    (";", "SEMI"),
    (":", "COLON"),
    ("::", "COLON2"),
    (",", "COMMA"),
    (".", "DOT"),
    ("?", "QUESTION"),
    ("=", "EQ"),
    ("<", "LT"),
    (">", "GT"),
];

const TERMINALS: &[(&str, &str)] = &[("ident", "IDENT"), ("typename", "IDENT"), ("str", "STRING")];

const TRIVIAL: &[&str] = &["WHITESPACE", "COMMENT"];
const SPECIAL: &[&str] = &["ERROR", "EOF"];
const LITERALS: &[&str] = &["STRING"];

pub fn generate() -> Result<(), Box<dyn Error>> {
    let source = fs::read_to_string(GRAMMAR)?;
    let grammar: Grammar = source.parse()?;

    let mut kinds = BTreeSet::new();
    let mut keywords = BTreeMap::new();

    for (_, kind) in PUNCTUATION {
        kinds.insert(kind.to_string());
    }

    for (_, kind) in TERMINALS {
        kinds.insert(kind.to_string());
    }

    for kind in TRIVIAL {
        kinds.insert(kind.to_string());
    }

    for kind in SPECIAL {
        kinds.insert(kind.to_string());
    }

    for kind in LITERALS {
        kinds.insert(kind.to_string());
    }

    for token in grammar.tokens() {
        let name = &grammar[token].name;

        // Terminal
        if let Some((_, kind)) = TERMINALS.iter().find(|(token, _)| *token == name) {
            kinds.insert((*kind).to_owned());
            continue;
        }

        // Keywords
        if name.starts_with(|c: char| c.is_lowercase()) {
            let kind = format!("{}_KW", name.to_shouty_snake_case());
            keywords.insert(name.clone(), kind.clone());
            kinds.insert(kind);
        }
    }

    for node in grammar.iter() {
        let name = &grammar[node].name;
        let kind = name.to_shouty_snake_case();
        kinds.insert(kind);
    }

    let variants: Vec<_> = kinds.iter().map(|kind| format_ident!("{kind}")).collect();

    let keyword_text: Vec<_> = keywords.keys().collect();
    let keyword_kind: Vec<_> = keywords
        .values()
        .map(|kind| format_ident!("{kind}"))
        .collect();

    let is_trivial: Vec<_> = TRIVIAL.iter().map(|kind| format_ident!("{kind}")).collect();
    let is_punctuation: Vec<_> = PUNCTUATION
        .iter()
        .map(|(_, kind)| format_ident!("{kind}"))
        .collect();

    let is_keyword: Vec<_> = keywords
        .values()
        .map(|kind| format_ident!("{kind}"))
        .collect();

    let is_literal: Vec<_> = LITERALS
        .iter()
        .map(|kind| format_ident!("{kind}"))
        .collect();

    let tokens = quote! {
        //! Generated by `cargo xtask ungram schema`.

        /// Syntax kinds for Cedar schemas.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        #[repr(u8)]
        #[expect(
            non_camel_case_types,
            clippy::upper_case_acronyms,
            reason = "Generated code"
        )]
        pub enum SchemaKind {
            #(#variants,)*
        }

        impl SchemaKind {
            /// Returns `true` if this is trivial.
            #[inline]
            #[must_use]
            pub const fn is_trivial(self) -> bool {
                matches!(self, #(Self::#is_trivial)|*)
            }

            /// Returns `true` if this is a keyword.
            #[inline]
            #[must_use]
            pub const fn is_keyword(self) -> bool {
                matches!(self, #(Self::#is_keyword)|*)
            }

            /// Returns `true` if this is punctuation.
            #[inline]
            #[must_use]
            pub const fn is_punctuation(self) -> bool {
                matches!(self, #(Self::#is_punctuation)|*)
            }

            /// Returns `true` if this is a literal.
            #[inline]
            #[must_use]
            pub const fn is_literal(self) -> bool {
                matches!(self, #(Self::#is_literal)|*)
            }

            /// Returns `true` if this is an error.
            #[inline]
            #[must_use]
            pub const fn is_error(self) -> bool {
                matches!(self, Self::ERROR)
            }

            /// Returns the keyword kind for the given text, if any.
            #[must_use]
            pub fn from_keyword(value: &str) -> Option<Self> {
                match value {
                    #(#keyword_text => Some(Self::#keyword_kind),)*
                    _ => None,
                }
            }
        }
    };

    let syntax = syn::parse_file(&tokens.to_string())?;
    let output = prettyplease::unparse(&syntax);
    fs::write(OUTPUT, output)?;

    Ok(())
}
