use alloc::collections::{BTreeMap, BTreeSet};
use core::error::Error;
use std::fs;

use heck::ToShoutySnakeCase as _;
use quote::{format_ident, quote};
use ungrammar::Grammar;

const TRIVIAL: &[&str] = &["WHITESPACE", "COMMENT"];
const SPECIAL: &[&str] = &["ERROR", "EOF"];

pub struct Config {
    pub grammar: &'static str,
    pub output: &'static str,

    pub name: &'static str,
    pub comment: &'static str,

    pub punctuation: &'static [(&'static str, &'static str)],
    pub tokens: &'static [(&'static str, &'static str)],
    pub literals: &'static [&'static str],
}

pub fn generate(config: &Config) -> Result<(), Box<dyn Error>> {
    let source = fs::read_to_string(config.grammar)?;
    let grammar: Grammar = source.parse()?;

    let mut kinds = BTreeSet::new();
    let mut keywords = BTreeMap::new();

    for (_, kind) in config.punctuation {
        kinds.insert(kind.to_string());
    }

    for kind in TRIVIAL.iter().chain(SPECIAL) {
        kinds.insert(kind.to_string());
    }

    for kind in config.literals {
        kinds.insert(kind.to_string());
    }

    for (_, kind) in config.tokens {
        kinds.insert(kind.to_string());
    }

    for token in grammar.tokens() {
        let name = &grammar[token].name;

        // Skip literals
        if config.tokens.iter().any(|(term, _)| *term == name) {
            continue;
        }

        // Skip punctuations
        if config.punctuation.iter().any(|(punct, _)| *punct == name) {
            continue;
        }

        // Only keywords
        if name.starts_with(|char: char| char.is_alphabetic()) {
            let kind = format!("{}_KW", name.to_shouty_snake_case());
            keywords.insert(name.clone(), kind.clone());
            kinds.insert(kind);
        }
    }

    for node in grammar.iter() {
        let name = &grammar[node].name;
        let kind = name.to_shouty_snake_case();
        kinds.insert(kind);
    }

    let name = format_ident!("{}", config.name);
    let variants: Vec<_> = kinds.iter().map(|kind| format_ident!("{kind}")).collect();

    let keyword_text: Vec<_> = keywords.keys().collect();
    let keyword_kind: Vec<_> = keywords
        .values()
        .map(|kind| format_ident!("{kind}"))
        .collect();

    let is_trivial: Vec<_> = TRIVIAL.iter().map(|kind| format_ident!("{kind}")).collect();
    let is_punctuation: Vec<_> = config
        .punctuation
        .iter()
        .map(|(_, kind)| format_ident!("{kind}"))
        .collect();
    let is_keyword: Vec<_> = keywords
        .values()
        .map(|kind| format_ident!("{kind}"))
        .collect();
    let is_literal: Vec<_> = config
        .literals
        .iter()
        .map(|kind| format_ident!("{kind}"))
        .collect();

    let comment = format!(" {}", config.comment);
    let tokens = quote! {
        //! Generated by `cargo xtask ungram`.

        #[doc = #comment]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        #[repr(u8)]
        #[expect(
            non_camel_case_types,
            clippy::upper_case_acronyms,
            reason = "Generated code"
        )]
        pub enum #name {
            #(#variants,)*
        }

        impl #name {
            /// Returns `true` if this is trivial.
            #[inline]
            #[must_use]
            pub const fn is_trivial(self) -> bool {
                matches!(self, #(Self::#is_trivial)|*)
            }

            /// Returns `true` if this is a keyword.
            #[inline]
            #[must_use]
            pub const fn is_keyword(self) -> bool {
                matches!(self, #(Self::#is_keyword)|*)
            }

            /// Returns `true` if this is punctuation.
            #[inline]
            #[must_use]
            pub const fn is_punctuation(self) -> bool {
                matches!(self, #(Self::#is_punctuation)|*)
            }

            /// Returns `true` if this is a literal.
            #[inline]
            #[must_use]
            pub const fn is_literal(self) -> bool {
                matches!(self, #(Self::#is_literal)|*)
            }

            /// Returns `true` if this is an error.
            #[inline]
            #[must_use]
            pub const fn is_error(self) -> bool {
                matches!(self, Self::ERROR)
            }

            /// Returns the keyword kind for the given text, if any.
            #[must_use]
            pub fn from_keyword(value: &str) -> Option<Self> {
                match value {
                    #(#keyword_text => Some(Self::#keyword_kind),)*
                    _ => None,
                }
            }
        }
    };

    let syntax = syn::parse_file(&tokens.to_string())?;
    let output = prettyplease::unparse(&syntax);
    fs::write(config.output, output)?;

    Ok(())
}
