//! Generated by `cargo xtask ungram policy`.
/// Syntax kinds for Cedar policies.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
#[expect(
    non_camel_case_types,
    clippy::upper_case_acronyms,
    reason = "Generated code"
)]
pub enum PolicyKind {
    ACCESS,
    ACTION,
    ACTION_KW,
    ADD,
    AMP2,
    AND,
    ANNOTATION,
    ANYIDENT,
    AT,
    BANG,
    BOOL,
    COLON,
    COLON2,
    COMMA,
    COMMENT,
    CONDITION,
    CONTEXT_KW,
    DOT,
    EFFECT,
    ELSE_KW,
    ENTITY,
    ENT_LIST,
    EOF,
    EQ2,
    ERROR,
    EXPR,
    EXPR_LIST,
    EXT_FUN,
    FALSE_KW,
    FORBID_KW,
    GT,
    GTEQ,
    HAS_KW,
    IDENT,
    IF_KW,
    INT,
    IN_KW,
    IS_KW,
    LIKE_KW,
    LITERAL,
    LT,
    LTEQ,
    L_BRACE,
    L_BRACKET,
    L_PAREN,
    MEMBER,
    MINUS,
    MULT,
    NEQ,
    OR,
    PAT,
    PATH,
    PATTERN,
    PERCENT,
    PERMIT_KW,
    PIPE2,
    PLUS,
    POLICIES,
    POLICY,
    PRIMARY,
    PRINCIPAL,
    PRINCIPAL_KW,
    PRINCIPAL_SLOT,
    QUESTION,
    REC_INITS,
    RELATION,
    RELOP,
    RESERVED,
    RESOURCE,
    RESOURCE_KW,
    RESOURCE_SLOT,
    R_BRACE,
    R_BRACKET,
    R_PAREN,
    SCOPE,
    SEMI,
    SLASH,
    STAR,
    STR,
    STRING,
    THEN_KW,
    TRUE_KW,
    UNARY,
    UNLESS_KW,
    VAR,
    WHEN_KW,
    WHITESPACE,
}
impl PolicyKind {
    /// Returns `true` if this is trivial.
    #[inline]
    #[must_use]
    pub const fn is_trivial(self) -> bool {
        matches!(self, Self::WHITESPACE | Self::COMMENT)
    }

    /// Returns `true` if this is a keyword.
    #[inline]
    #[must_use]
    pub const fn is_keyword(self) -> bool {
        matches!(
            self,
            Self::ACTION_KW
                | Self::CONTEXT_KW
                | Self::ELSE_KW
                | Self::FALSE_KW
                | Self::FORBID_KW
                | Self::HAS_KW
                | Self::IF_KW
                | Self::IN_KW
                | Self::IS_KW
                | Self::LIKE_KW
                | Self::PERMIT_KW
                | Self::PRINCIPAL_KW
                | Self::RESOURCE_KW
                | Self::THEN_KW
                | Self::TRUE_KW
                | Self::UNLESS_KW
                | Self::WHEN_KW
        )
    }

    /// Returns `true` if this is punctuation.
    #[inline]
    #[must_use]
    pub const fn is_punctuation(self) -> bool {
        matches!(
            self,
            Self::AT
                | Self::L_PAREN
                | Self::R_PAREN
                | Self::L_BRACE
                | Self::R_BRACE
                | Self::L_BRACKET
                | Self::R_BRACKET
                | Self::SEMI
                | Self::COLON
                | Self::COLON2
                | Self::COMMA
                | Self::DOT
                | Self::QUESTION
                | Self::EQ2
                | Self::NEQ
                | Self::LT
                | Self::LTEQ
                | Self::GT
                | Self::GTEQ
                | Self::AMP2
                | Self::PIPE2
                | Self::PLUS
                | Self::MINUS
                | Self::STAR
                | Self::SLASH
                | Self::PERCENT
                | Self::BANG
                | Self::PRINCIPAL_SLOT
                | Self::RESOURCE_SLOT
        )
    }

    /// Returns `true` if this is a literal.
    #[inline]
    #[must_use]
    pub const fn is_literal(self) -> bool {
        matches!(self, Self::INT | Self::STRING | Self::PATTERN)
    }

    /// Returns `true` if this is an error.
    #[inline]
    #[must_use]
    pub const fn is_error(self) -> bool {
        matches!(self, Self::ERROR)
    }

    /// Returns the keyword kind for the given text, if any.
    #[must_use]
    pub fn from_keyword(value: &str) -> Option<Self> {
        match value {
            "action" => Some(Self::ACTION_KW),
            "context" => Some(Self::CONTEXT_KW),
            "else" => Some(Self::ELSE_KW),
            "false" => Some(Self::FALSE_KW),
            "forbid" => Some(Self::FORBID_KW),
            "has" => Some(Self::HAS_KW),
            "if" => Some(Self::IF_KW),
            "in" => Some(Self::IN_KW),
            "is" => Some(Self::IS_KW),
            "like" => Some(Self::LIKE_KW),
            "permit" => Some(Self::PERMIT_KW),
            "principal" => Some(Self::PRINCIPAL_KW),
            "resource" => Some(Self::RESOURCE_KW),
            "then" => Some(Self::THEN_KW),
            "true" => Some(Self::TRUE_KW),
            "unless" => Some(Self::UNLESS_KW),
            "when" => Some(Self::WHEN_KW),
            _ => None,
        }
    }
}
