// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(message, optional, tag = "1")]
    pub principal: ::core::option::Option<EntityUid>,
    #[prost(message, optional, tag = "2")]
    pub action: ::core::option::Option<EntityUid>,
    #[prost(message, optional, tag = "3")]
    pub resource: ::core::option::Option<EntityUid>,
    #[prost(map = "string, message", tag = "4")]
    pub context: ::std::collections::HashMap<::prost::alloc::string::String, Expr>,
}
/// the protobuf PolicySet message describes a complete policy set, including
/// templates, static policies, and/or template-linked policies.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PolicySet {
    /// Both templates and static policies are included here, with static
    /// policies represented as templates with zero slots.
    #[prost(message, repeated, tag = "1")]
    pub templates: ::prost::alloc::vec::Vec<TemplateBody>,
    /// All static policies and template-linked policies are included here.
    /// Static policies must appear exactly once, and the PolicyID of the static
    /// policy must be the same in this list and the above list.
    #[prost(message, repeated, tag = "2")]
    pub links: ::prost::alloc::vec::Vec<Policy>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entities {
    #[prost(message, repeated, tag = "1")]
    pub entities: ::prost::alloc::vec::Vec<Entity>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EntityUid {
    #[prost(message, optional, tag = "1")]
    pub ty: ::core::option::Option<Name>,
    #[prost(string, tag = "2")]
    pub eid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Name {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// the protobuf Policy message describes either a static or a template-linked policy.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Policy {
    /// ID of the template associated with this policy.
    /// For static policies, this is the ID of a zero-slot template.
    #[prost(string, tag = "1")]
    pub template_id: ::prost::alloc::string::String,
    /// ID of this policy itself.
    /// For static policies, this is omitted/ignored; the ID of the policy is the
    /// `template_id`.
    #[prost(string, optional, tag = "2")]
    pub link_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether this policy is a static (false) or template-linked (true) policy
    #[prost(bool, tag = "3")]
    pub is_template_link: bool,
    /// Value of the `?principal` slot.
    /// Omitted/ignored for templates without the `?principal` slot.
    #[prost(message, optional, tag = "4")]
    pub principal_euid: ::core::option::Option<EntityUid>,
    /// Value of the `?resource` slot.
    /// Omitted/ignored for templates without the `?resource` slot.
    #[prost(message, optional, tag = "5")]
    pub resource_euid: ::core::option::Option<EntityUid>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TemplateBody {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(enumeration = "Effect", tag = "4")]
    pub effect: i32,
    #[prost(message, optional, tag = "5")]
    pub principal_constraint: ::core::option::Option<PrincipalOrResourceConstraint>,
    #[prost(message, optional, tag = "6")]
    pub action_constraint: ::core::option::Option<ActionConstraint>,
    #[prost(message, optional, tag = "7")]
    pub resource_constraint: ::core::option::Option<PrincipalOrResourceConstraint>,
    #[prost(message, optional, tag = "8")]
    pub non_scope_constraints: ::core::option::Option<Expr>,
}
/// an EntityReference may either be an EntityUid or a Slot.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EntityReference {
    #[prost(oneof = "entity_reference::Data", tags = "1, 2")]
    pub data: ::core::option::Option<entity_reference::Data>,
}
/// Nested message and enum types in `EntityReference`.
pub mod entity_reference {
    /// if it's a Slot, we know from context which Slot it is,
    /// so we don't need a `SlotId` and can just use this one-armed enum
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Slot {
        /// the one option for the enum
        Unit = 0,
    }
    impl Slot {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unit => "unit",
            }
        }

        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "unit" => Some(Self::Unit),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(enumeration = "Slot", tag = "1")]
        Slot(i32),
        #[prost(message, tag = "2")]
        Euid(super::EntityUid),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrincipalOrResourceConstraint {
    #[prost(
        oneof = "principal_or_resource_constraint::Data",
        tags = "1, 2, 3, 4, 5"
    )]
    pub data: ::core::option::Option<principal_or_resource_constraint::Data>,
}
/// Nested message and enum types in `PrincipalOrResourceConstraint`.
pub mod principal_or_resource_constraint {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct InMessage {
        #[prost(message, optional, tag = "1")]
        pub er: ::core::option::Option<super::EntityReference>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct EqMessage {
        #[prost(message, optional, tag = "1")]
        pub er: ::core::option::Option<super::EntityReference>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct IsMessage {
        #[prost(message, optional, tag = "1")]
        pub entity_type: ::core::option::Option<super::Name>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct IsInMessage {
        #[prost(message, optional, tag = "1")]
        pub er: ::core::option::Option<super::EntityReference>,
        #[prost(message, optional, tag = "2")]
        pub entity_type: ::core::option::Option<super::Name>,
    }
    /// Zero-arity constructors represented as enums with only one member
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Any {
        /// the one option for the enum
        Unit = 0,
    }
    impl Any {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unit => "unit",
            }
        }

        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "unit" => Some(Self::Unit),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(enumeration = "Any", tag = "1")]
        Any(i32),
        #[prost(message, tag = "2")]
        In(InMessage),
        #[prost(message, tag = "3")]
        Eq(EqMessage),
        #[prost(message, tag = "4")]
        Is(IsMessage),
        #[prost(message, tag = "5")]
        IsIn(IsInMessage),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActionConstraint {
    #[prost(oneof = "action_constraint::Data", tags = "1, 2, 3")]
    pub data: ::core::option::Option<action_constraint::Data>,
}
/// Nested message and enum types in `ActionConstraint`.
pub mod action_constraint {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct InMessage {
        #[prost(message, repeated, tag = "1")]
        pub euids: ::prost::alloc::vec::Vec<super::EntityUid>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct EqMessage {
        #[prost(message, optional, tag = "1")]
        pub euid: ::core::option::Option<super::EntityUid>,
    }
    /// Zero-arity constructors represented as enums with only one member
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Any {
        /// the one option for the enum
        Unit = 0,
    }
    impl Any {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unit => "unit",
            }
        }

        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "unit" => Some(Self::Unit),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(enumeration = "Any", tag = "1")]
        Any(i32),
        #[prost(message, tag = "2")]
        In(InMessage),
        #[prost(message, tag = "3")]
        Eq(EqMessage),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Expr {
    #[prost(
        oneof = "expr::ExprKind",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15"
    )]
    pub expr_kind: ::core::option::Option<expr::ExprKind>,
}
/// Nested message and enum types in `Expr`.
pub mod expr {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Literal {
        #[prost(oneof = "literal::Lit", tags = "1, 2, 3, 4")]
        pub lit: ::core::option::Option<literal::Lit>,
    }
    /// Nested message and enum types in `Literal`.
    pub mod literal {
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
        pub enum Lit {
            #[prost(bool, tag = "1")]
            B(bool),
            #[prost(int64, tag = "2")]
            I(i64),
            #[prost(string, tag = "3")]
            S(::prost::alloc::string::String),
            #[prost(message, tag = "4")]
            Euid(super::super::EntityUid),
        }
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct If {
        #[prost(message, optional, boxed, tag = "1")]
        pub test_expr: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(message, optional, boxed, tag = "2")]
        pub then_expr: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(message, optional, boxed, tag = "3")]
        pub else_expr: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct And {
        #[prost(message, optional, boxed, tag = "1")]
        pub left: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(message, optional, boxed, tag = "2")]
        pub right: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Or {
        #[prost(message, optional, boxed, tag = "1")]
        pub left: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(message, optional, boxed, tag = "2")]
        pub right: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UnaryApp {
        #[prost(enumeration = "unary_app::Op", tag = "1")]
        pub op: i32,
        #[prost(message, optional, boxed, tag = "2")]
        pub expr: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
    }
    /// Nested message and enum types in `UnaryApp`.
    pub mod unary_app {
        #[derive(
            Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration,
        )]
        #[repr(i32)]
        pub enum Op {
            Not = 0,
            Neg = 1,
            IsEmpty = 2,
        }
        impl Op {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Not => "Not",
                    Self::Neg => "Neg",
                    Self::IsEmpty => "IsEmpty",
                }
            }

            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "Not" => Some(Self::Not),
                    "Neg" => Some(Self::Neg),
                    "IsEmpty" => Some(Self::IsEmpty),
                    _ => None,
                }
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct BinaryApp {
        #[prost(enumeration = "binary_app::Op", tag = "1")]
        pub op: i32,
        #[prost(message, optional, boxed, tag = "2")]
        pub left: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(message, optional, boxed, tag = "3")]
        pub right: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
    }
    /// Nested message and enum types in `BinaryApp`.
    pub mod binary_app {
        #[derive(
            Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration,
        )]
        #[repr(i32)]
        pub enum Op {
            Eq = 0,
            Less = 1,
            LessEq = 2,
            Add = 3,
            Sub = 4,
            Mul = 5,
            In = 6,
            Contains = 7,
            ContainsAll = 8,
            ContainsAny = 9,
            GetTag = 10,
            HasTag = 11,
        }
        impl Op {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Eq => "Eq",
                    Self::Less => "Less",
                    Self::LessEq => "LessEq",
                    Self::Add => "Add",
                    Self::Sub => "Sub",
                    Self::Mul => "Mul",
                    Self::In => "In",
                    Self::Contains => "Contains",
                    Self::ContainsAll => "ContainsAll",
                    Self::ContainsAny => "ContainsAny",
                    Self::GetTag => "GetTag",
                    Self::HasTag => "HasTag",
                }
            }

            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "Eq" => Some(Self::Eq),
                    "Less" => Some(Self::Less),
                    "LessEq" => Some(Self::LessEq),
                    "Add" => Some(Self::Add),
                    "Sub" => Some(Self::Sub),
                    "Mul" => Some(Self::Mul),
                    "In" => Some(Self::In),
                    "Contains" => Some(Self::Contains),
                    "ContainsAll" => Some(Self::ContainsAll),
                    "ContainsAny" => Some(Self::ContainsAny),
                    "GetTag" => Some(Self::GetTag),
                    "HasTag" => Some(Self::HasTag),
                    _ => None,
                }
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ExtensionFunctionApp {
        #[prost(message, optional, tag = "1")]
        pub fn_name: ::core::option::Option<super::Name>,
        #[prost(message, repeated, tag = "2")]
        pub args: ::prost::alloc::vec::Vec<super::Expr>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct GetAttr {
        #[prost(message, optional, boxed, tag = "1")]
        pub expr: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(string, tag = "2")]
        pub attr: ::prost::alloc::string::String,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct HasAttr {
        #[prost(message, optional, boxed, tag = "1")]
        pub expr: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(string, tag = "2")]
        pub attr: ::prost::alloc::string::String,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Like {
        #[prost(message, optional, boxed, tag = "1")]
        pub expr: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(message, repeated, tag = "2")]
        pub pattern: ::prost::alloc::vec::Vec<like::PatternElem>,
    }
    /// Nested message and enum types in `Like`.
    pub mod like {
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct PatternElem {
            #[prost(oneof = "pattern_elem::Data", tags = "1, 2")]
            pub data: ::core::option::Option<pattern_elem::Data>,
        }
        /// Nested message and enum types in `PatternElem`.
        pub mod pattern_elem {
            /// Zero-arity constructors represented as enums with only one member
            #[derive(
                Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration,
            )]
            #[repr(i32)]
            pub enum Wildcard {
                /// the one option for the enum
                Unit = 0,
            }
            impl Wildcard {
                /// String value of the enum field names used in the ProtoBuf definition.
                ///
                /// The values are not transformed in any way and thus are considered stable
                /// (if the ProtoBuf definition does not change) and safe for programmatic use.
                pub fn as_str_name(&self) -> &'static str {
                    match self {
                        Self::Unit => "unit",
                    }
                }

                /// Creates an enum from field names used in the ProtoBuf definition.
                pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                    match value {
                        "unit" => Some(Self::Unit),
                        _ => None,
                    }
                }
            }
            #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
            pub enum Data {
                #[prost(enumeration = "Wildcard", tag = "1")]
                Wildcard(i32),
                #[prost(string, tag = "2")]
                C(::prost::alloc::string::String),
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Is {
        #[prost(message, optional, boxed, tag = "1")]
        pub expr: ::core::option::Option<::prost::alloc::boxed::Box<super::Expr>>,
        #[prost(message, optional, tag = "2")]
        pub entity_type: ::core::option::Option<super::Name>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Set {
        #[prost(message, repeated, tag = "1")]
        pub elements: ::prost::alloc::vec::Vec<super::Expr>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Record {
        #[prost(map = "string, message", tag = "1")]
        pub items: ::std::collections::HashMap<::prost::alloc::string::String, super::Expr>,
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Var {
        Principal = 0,
        Action = 1,
        Resource = 2,
        Context = 3,
    }
    impl Var {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Principal => "Principal",
                Self::Action => "Action",
                Self::Resource => "Resource",
                Self::Context => "Context",
            }
        }

        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Principal" => Some(Self::Principal),
                "Action" => Some(Self::Action),
                "Resource" => Some(Self::Resource),
                "Context" => Some(Self::Context),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ExprKind {
        #[prost(message, tag = "1")]
        Lit(Literal),
        #[prost(enumeration = "Var", tag = "2")]
        Var(i32),
        #[prost(enumeration = "super::SlotId", tag = "3")]
        Slot(i32),
        #[prost(message, tag = "4")]
        If(::prost::alloc::boxed::Box<If>),
        #[prost(message, tag = "5")]
        And(::prost::alloc::boxed::Box<And>),
        #[prost(message, tag = "6")]
        Or(::prost::alloc::boxed::Box<Or>),
        #[prost(message, tag = "7")]
        UApp(::prost::alloc::boxed::Box<UnaryApp>),
        #[prost(message, tag = "8")]
        BApp(::prost::alloc::boxed::Box<BinaryApp>),
        #[prost(message, tag = "9")]
        ExtApp(ExtensionFunctionApp),
        #[prost(message, tag = "10")]
        GetAttr(::prost::alloc::boxed::Box<GetAttr>),
        #[prost(message, tag = "11")]
        HasAttr(::prost::alloc::boxed::Box<HasAttr>),
        #[prost(message, tag = "12")]
        Like(::prost::alloc::boxed::Box<Like>),
        #[prost(message, tag = "13")]
        Is(::prost::alloc::boxed::Box<Is>),
        #[prost(message, tag = "14")]
        Set(Set),
        #[prost(message, tag = "15")]
        Record(Record),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entity {
    #[prost(message, optional, tag = "1")]
    pub uid: ::core::option::Option<EntityUid>,
    #[prost(map = "string, message", tag = "2")]
    pub attrs: ::std::collections::HashMap<::prost::alloc::string::String, Expr>,
    #[prost(message, repeated, tag = "3")]
    pub ancestors: ::prost::alloc::vec::Vec<EntityUid>,
    #[prost(map = "string, message", tag = "4")]
    pub tags: ::std::collections::HashMap<::prost::alloc::string::String, Expr>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Effect {
    Forbid = 0,
    Permit = 1,
}
impl Effect {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Forbid => "Forbid",
            Self::Permit => "Permit",
        }
    }

    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Forbid" => Some(Self::Forbid),
            "Permit" => Some(Self::Permit),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SlotId {
    Principal = 0,
    Resource = 1,
}
impl SlotId {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Principal => "Principal",
            Self::Resource => "Resource",
        }
    }

    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Principal" => Some(Self::Principal),
            "Resource" => Some(Self::Resource),
            _ => None,
        }
    }
}
