//! Generated by `cargo xtask ungram schema`.
/// Syntax kinds for Cedar schemas.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
#[expect(
    non_camel_case_types,
    clippy::upper_case_acronyms,
    reason = "Generated code"
)]
pub enum SchemaKind {
    ACTION,
    ACTION_KW,
    ANNOTATION,
    ANNOTATIONS,
    APPLIES_TO,
    APPLIES_TO_KW,
    APP_DECLS,
    AT,
    ATTR_DECLS,
    BOOLEAN_KW,
    BOOL_KW,
    COLON,
    COLON2,
    COMMA,
    COMMENT,
    CONTEXT_KW,
    DECL,
    DOT,
    ENTITY,
    ENTITY_KW,
    ENT_OR_TYPS,
    ENT_TYPE,
    ENT_TYPES,
    ENUM_KW,
    ENUM_VARIANTS,
    EOF,
    EQ,
    ERROR,
    EXTENSION_KW,
    GT,
    IDENT,
    IDENTS,
    IN_KW,
    LONG_KW,
    LT,
    L_BRACE,
    L_BRACKET,
    L_PAREN,
    NAME,
    NAMES,
    NAMESPACE,
    NAMESPACE_KW,
    PATH,
    PRIMTYPE,
    PRINCIPAL_KW,
    QUESTION,
    RECORD_KW,
    REC_TYPE,
    REF,
    REF_OR_REFS,
    RESERVED,
    RESOURCE_KW,
    R_BRACE,
    R_BRACKET,
    R_PAREN,
    SCHEMA,
    SEMI,
    SET_KW,
    SET_TYPE,
    STR,
    STRING,
    STRING_KW,
    TAGS_KW,
    TYPE,
    TYPENAME,
    TYPE_DECL,
    TYPE_KW,
    WHITESPACE,
}
impl SchemaKind {
    /// Returns `true` if this is trivial.
    #[inline]
    #[must_use]
    pub const fn is_trivial(self) -> bool {
        matches!(self, Self::WHITESPACE | Self::COMMENT)
    }

    /// Returns `true` if this is a keyword.
    #[inline]
    #[must_use]
    pub const fn is_keyword(self) -> bool {
        matches!(
            self,
            Self::ACTION_KW
                | Self::APPLIES_TO_KW
                | Self::BOOLEAN_KW
                | Self::BOOL_KW
                | Self::CONTEXT_KW
                | Self::ENTITY_KW
                | Self::ENUM_KW
                | Self::EXTENSION_KW
                | Self::IN_KW
                | Self::LONG_KW
                | Self::NAMESPACE_KW
                | Self::PRINCIPAL_KW
                | Self::RECORD_KW
                | Self::RESOURCE_KW
                | Self::SET_KW
                | Self::STRING_KW
                | Self::TAGS_KW
                | Self::TYPE_KW
        )
    }

    /// Returns `true` if this is punctuation.
    #[inline]
    #[must_use]
    pub const fn is_punctuation(self) -> bool {
        matches!(
            self,
            Self::AT
                | Self::L_PAREN
                | Self::R_PAREN
                | Self::L_BRACE
                | Self::R_BRACE
                | Self::L_BRACKET
                | Self::R_BRACKET
                | Self::SEMI
                | Self::COLON
                | Self::COLON2
                | Self::COMMA
                | Self::DOT
                | Self::QUESTION
                | Self::EQ
                | Self::LT
                | Self::GT
        )
    }

    /// Returns `true` if this is a literal.
    #[inline]
    #[must_use]
    pub const fn is_literal(self) -> bool {
        matches!(self, Self::STRING)
    }

    /// Returns `true` if this is an error.
    #[inline]
    #[must_use]
    pub const fn is_error(self) -> bool {
        matches!(self, Self::ERROR)
    }
}
