//! Generated by `cargo xtask ungram`.
/// Syntax kinds for Cedar schemas.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
#[expect(
    non_camel_case_types,
    clippy::upper_case_acronyms,
    reason = "Generated code"
)]
pub enum SchemaKind {
    ACTION,
    ACTION_ATTRS,
    ACTION_KW,
    ACTION_PARENTS,
    ANNOTATION,
    APPLIES_TO,
    APPLIES_TO_KW,
    APP_DECL,
    APP_DECLS,
    AT,
    ATTRIBUTES_KW,
    ATTR_DECL,
    ATTR_DECLS,
    BOOL_KW,
    COLON,
    COLON2,
    COMMA,
    COMMENT,
    CONTEXT_DECL,
    CONTEXT_KW,
    CONTEXT_TYPE,
    DECL,
    DOT,
    ENTITY,
    ENTITY_ATTRS,
    ENTITY_ENUM,
    ENTITY_KW,
    ENTITY_STANDARD,
    ENT_TYPES,
    ENUM_KW,
    EOF,
    EQ,
    ERROR,
    GT,
    IDENT,
    IDENTS,
    IN_KW,
    LONG_KW,
    LT,
    L_BRACE,
    L_BRACKET,
    L_PAREN,
    MEMBER_OF,
    NAME,
    NAMES,
    NAMESPACE,
    NAMESPACE_BODY,
    NAMESPACE_DECL,
    NAMESPACE_KW,
    PATH,
    PATH_LIST,
    PRINCIPAL_KW,
    PRINCIPAL_OR_RESOURCE,
    QUAL_NAME,
    QUAL_NAME_LIST,
    QUAL_NAME_OR_NAMES,
    QUESTION,
    REC_TYPE,
    RESOURCE_KW,
    R_BRACE,
    R_BRACKET,
    R_PAREN,
    SCHEMA,
    SEMI,
    SET_KW,
    SET_TYPE,
    STRING,
    STRINGS,
    STRING_KW,
    TAGS,
    TAGS_KW,
    TYPE,
    TYPE_DECL,
    TYPE_KW,
    WHITESPACE,
}
impl SchemaKind {
    /// Returns `true` if this is trivial.
    #[inline]
    #[must_use]
    pub const fn is_trivial(self) -> bool {
        matches!(self, Self::WHITESPACE | Self::COMMENT)
    }

    /// Returns `true` if this is a keyword.
    #[inline]
    #[must_use]
    pub const fn is_keyword(self) -> bool {
        matches!(
            self,
            Self::BOOL_KW
                | Self::LONG_KW
                | Self::SET_KW
                | Self::STRING_KW
                | Self::ACTION_KW
                | Self::APPLIES_TO_KW
                | Self::ATTRIBUTES_KW
                | Self::CONTEXT_KW
                | Self::ENTITY_KW
                | Self::ENUM_KW
                | Self::IN_KW
                | Self::NAMESPACE_KW
                | Self::PRINCIPAL_KW
                | Self::RESOURCE_KW
                | Self::TAGS_KW
                | Self::TYPE_KW
        )
    }

    /// Returns `true` if this is punctuation.
    #[inline]
    #[must_use]
    pub const fn is_punctuation(self) -> bool {
        matches!(
            self,
            Self::AT
                | Self::L_PAREN
                | Self::R_PAREN
                | Self::L_BRACE
                | Self::R_BRACE
                | Self::L_BRACKET
                | Self::R_BRACKET
                | Self::SEMI
                | Self::COLON
                | Self::COLON2
                | Self::COMMA
                | Self::DOT
                | Self::QUESTION
                | Self::EQ
                | Self::LT
                | Self::GT
        )
    }

    /// Returns `true` if this is a literal.
    #[inline]
    #[must_use]
    pub const fn is_literal(self) -> bool {
        matches!(self, Self::STRING)
    }

    /// Returns `true` if this is an error.
    #[inline]
    #[must_use]
    pub const fn is_error(self) -> bool {
        matches!(self, Self::ERROR)
    }

    /// Returns the keyword kind for the given text, if any.
    #[must_use]
    pub fn from_keyword(value: &str) -> Option<Self> {
        match value {
            "Bool" => Some(Self::BOOL_KW),
            "Long" => Some(Self::LONG_KW),
            "Set" => Some(Self::SET_KW),
            "String" => Some(Self::STRING_KW),
            "action" => Some(Self::ACTION_KW),
            "appliesTo" => Some(Self::APPLIES_TO_KW),
            "attributes" => Some(Self::ATTRIBUTES_KW),
            "context" => Some(Self::CONTEXT_KW),
            "entity" => Some(Self::ENTITY_KW),
            "enum" => Some(Self::ENUM_KW),
            "in" => Some(Self::IN_KW),
            "namespace" => Some(Self::NAMESPACE_KW),
            "principal" => Some(Self::PRINCIPAL_KW),
            "resource" => Some(Self::RESOURCE_KW),
            "tags" => Some(Self::TAGS_KW),
            "type" => Some(Self::TYPE_KW),
            _ => None,
        }
    }
}
